version: '2'

services:
    web:
        build: ./web
        container_name: livesports-web
        image: livesports-web
        ports:
            - ${APP_PORT}:80
        volumes:
            - ${APP_DIR}:/home/app:ro
        links:
            - php
        network_mode: bridge

    php:
        build: ./php
        container_name: livesports-php
        image: livesports-php
        volumes:
            - ${APP_DIR}:/home/app:cached
        links:
            - mercure
        network_mode: bridge
        working_dir: /home/app

    mercure:
        image: dunglas/mercure
        container_name: livesports-mercure
        ports:
            - 3000:3000
        environment:
            - ALLOW_ANONYMOUS=1
            - CORS_ALLOWED_ORIGINS=*
            - JWT_KEY=JorgeHRJ-JWTKey
            - PUBLISH_ALLOWED_ORIGINS=http://livesports.loc
            - ADDR=:3000
        network_mode: bridge
